platform:ios, '9.0'
target 'ChatFirebase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'JSQMessagesViewController'
  pod 'SVProgressHUD'
  pod 'SwiftLint'
  pod 'RDGliderViewController-Swift'

  target 'ChatFirebaseTests' do
    inherit!:search_paths
    # Pods for testing
  end

end
