# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'Survyy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Survyy
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SwiftLint'
  pod 'RDGliderViewController-Swift'

  target 'SurvyyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SurvyyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
