platform :ios, '9.0'
target 'Survyy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Survyy
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'JSQMessagesViewController'

  target 'SurvyyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
